# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0002_auto_20170328_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='list',
            new_name='list_id',
        ),
    ]
